### ISSUE TITLE
Cortex-M4 FVP platform

### ISSUE THREAD

**Issue by June0165** [ARM-software/Arm-2D#13]
where am I download Cortex-M4 FVP platform and how to use it?

**Comment by GorgonMeducer** [comment]
@June0165 Once you have installed MDK, you can find them in the installation folder (i.e. C:\Keil_v5\Arm\FVP). 
If you cannot find the FVP folder, for example, if you have installed the MDK 5.37, there is another folder called VHT (i.e. C:\Keil_v5\Arm\VHT). 

All projects in the example folder contain a configuration called FastModel. It is already configured to use FVP as debug target.

I hope this helps.

**Comment by GorgonMeducer** [comment]
Please note that, using FVP and/or VHT requires MDK professional license.

**Comment by June0165** [comment]
@GorgonMeducer Thank you so much. This is very useful to me!!!

**Comment by GorgonMeducer** [comment]
You are welcome.
