### ISSUE TITLE
Add an API for copy-tile-with-rounded-corner

### ISSUE THREAD

**Issue by gzbkey** [ARM-software/Arm-2D#43]
We need a method (or example control) to copy a given source tile to the target tile adding rounded corner automatically. 

It is better to allow users changing the corner mask. 

It is better to update the existing `draw_round_corner_border` and `draw_round_corner_box` to allow people to specify the corner mask.

**Comment by GorgonMeducer** [comment]
`draw_round_corner_image` has been added. 
`draw_round_corner_box` has been updated to support changing the corner mask. 
 Generic benchmark has been updated to show the example of drawing round corner Image.
