### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ARM-software/Arm-2D#46]
I would like to point out that an identifier like “[`__ARM_2D_H__`](https://github.com/ARM-software/Arm-2D/blob/2b729c9cb3b8d6b816be1a002455e197848b0478/Library/Include/arm_2d.h#L31-L32 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by GorgonMeducer** [comment]
Thank you for your feedback. 

We knew this naming convention, and similar to cms is and cmsis-dsp, arm-2d is part of the software infrastructure libraries provided by the arm for use with the arm toolchain.

https://github.com/search?q=repo%3AARM-software%2FCMSIS-DSP%20__&type=code

And you are right. For the application code and example code, we should avoid using `__` as the prefix. We will apply the change in the v1.1.6. 

Thank you very much.

I hope this answers your questions.

**Comment by GorgonMeducer** [comment]
By the way, Arm-2D is a C library but not C++, hence by checking.
![image](https://github.com/ARM-software/Arm-2D/assets/13148491/b480f14c-bbec-47cc-824c-a18bb45b256e)

https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier

We are open to further discussion.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/reserved-identifier.html "Checking the application of reserved identifiers")?

**Comment by elfring** [comment]
:thought_balloon: I hope that you would also like to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?").

**Comment by GorgonMeducer** [comment]
> :thought_balloon: I hope that you would also like to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?").

For this part, if you could point out detailed problem in a dedicated issue that would help. 

Thank you very much.

**Comment by GorgonMeducer** [comment]
Your impression is correct.

**Comment by elfring** [comment]
Which changes did improve the affected software?

**Comment by GorgonMeducer** [comment]
This is a question for arm developers; I know many who use the same manner, and I am definitely sure you know someone who doesn't like to use reserved identifiers.

I cannot represent any Arm developers, so I am not able to answer this question. Sorry.

**Comment by elfring** [comment]
>Unless I see solid evidence that the existing arm-2d identifier with "__" as their prefix conflicts with the reserved ones in arm c compilers that we claim to support, i.e. IAR, GCC, LLVM and Arm Compiler 5/6, I will not change my mind.

:thought_balloon: It seems that some source code reviewers were also too careless according to concerns around undefined behaviour so far.
:crystal_ball: Will development interests grow for better compliance with known programming rules?

**Comment by GorgonMeducer** [comment]
I am open to talking with you about this. 

Would you mind providing me with some solid cases that:
> existing arm-2d identifier with "__" as their prefix conflicts with the reserved ones in arm c compilers that we claim to support, i.e. IAR, GCC, LLVM and Arm Compiler 5/6,

This will help us to improve the project. 
Thank you.

**Comment by elfring** [comment]
:eyes: Did you overlook any warnings about undefined behaviour from linked information sources so far?

**Comment by GorgonMeducer** [comment]
It looks like a personal question for me, please allow me to keep the answers to myself.

For the arm-2d project, our team reviews all the warnings, evaluates the risks and treats them with different policies.
End users should see 0 warnings when using the arm compiler we claim to support.

if you address any warnings, please feel free to report them.  

Thank you.

**Comment by elfring** [comment]
>End users should see 0 warnings when using the arm compilers we claim to support.
>
>if you address any warnings, please feel free to report them.

:thought_balloon: I find such a feedback questionable according to discussed programming language compliance concerns.
Further source code analysis tools can help to reconsider remaining open issues, can't they? :thinking:

**Comment by GorgonMeducer** [comment]
We have yet to claim to follow the standard you mentioned. 
So I would put your suggestion as a new feature recommendation.

Thank you for your time.

**Comment by elfring** [comment]
>We have yet to claim to follow the standard you mentioned.

Does this software belong to the implementation for the programming language “C” (or “C++”)?

**Comment by GorgonMeducer** [comment]
Arm-2D is under Apache 2.0.
It is an open-source project. 
We have clearly mentioned in our document that "__" is used as an indicator of private symbols.

Those who use arm-2d should follow the Apache 2.0 license and manage their own risk.

**Comment by elfring** [comment]
>We have clearly mentioned in our document that "__" is used as an indicator of private symbols.

I interpret such information as a recurring programming mistake.

**Comment by GorgonMeducer** [comment]
I respect your judgement. Thank you.

**Comment by GorgonMeducer** [comment]
Please allow me to keep this personal question to myself.
