### ISSUE TITLE
Arm-2D can be used Arduino or PlatformIO

### ISSUE THREAD

**Issue by skylin008** [ARM-software/Arm-2D#55]
Thanks shared this impressive project。 Does Arm-2d can be used Arduino or PlatformIO, if there any porting guide?

**Comment by GorgonMeducer** [comment]
@skylin008 I think Arm-2D can be used in Arduino and PlatformIO. 
You can use Arm-2D for Cortex-M devices. It is also easy to port to other platforms, our [PC template (supporting Linux, Windows and MacOS)](https://github.com/ARM-software/Arm-2D/tree/main/examples/%5Btemplate%5D%5Bpc%5D%5Bvscode%5D) is a good example.

Arm-2D is friendly for porting. I think the [makefile](https://github.com/ARM-software/Arm-2D/blob/main/examples/%5Btemplate%5D%5Bpc%5D%5Bvscode%5D/Makefile) inside the PC project contains all the information you need.  
We also put some key porting files here: 
https://github.com/ARM-software/Arm-2D/tree/main/examples/porting/%5Bnon-arm%5D%5Bno-arm_math%5D%5Bgeneric%5D

I hope this helps.

If you have any specific questions, please feel free to raise an issue.
